/**
 * Build injectable context blocks for coding agents.
 */

import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import type { DecisionSummary, MemoryEntry, MemorySearchResult } from "@agentos/core";
import { AGENTOS_DIR, CONTEXT_FILE } from "@agentos/core";
import type { MemoryStore } from "@agentos/memory";

export interface ContextOptions {
  limit?: number;
  query?: string;
  preferDecisions?: boolean;
}

export function buildContextBlock(
  store: MemoryStore,
  options: ContextOptions = {}
): string {
  const limit = options.limit ?? 12;
  const preferDecisions = options.preferDecisions !== false;

  let results: MemorySearchResult[];

  if (options.query?.trim()) {
    results = store.search(options.query, { limit });
  } else {
    const decisions = store.list("decision").slice(-8);
    const project = store.list("project").slice(-4);
    const prefs = store.list("preference").slice(-4);
    const combined = [...decisions, ...project, ...prefs];
    results = combined.map((entry, i) => ({
      entry,
      score: combined.length - i,
    }));
  }

  if (preferDecisions) {
    results = [
      ...results.filter((r) => r.entry.type === "decision"),
      ...results.filter((r) => r.entry.type !== "decision"),
    ].slice(0, limit);
  } else {
    results = results.slice(0, limit);
  }

  if (results.length === 0) {
    return [
      "## AgentOS Memory",
      "",
      "_No institutional memory yet._",
      "",
      "When you make an architectural decision, record it:",
      "```bash",
      'npx agentos memory add "We chose X because Y"',
      "```",
      "",
    ].join("\n");
  }

  const lines: string[] = [
    "## AgentOS Institutional Memory",
    "",
    "Use this project memory before guessing. Prefer evidence over invention.",
    "",
  ];

  const decisions = results.filter((r) => r.entry.type === "decision");
  const other = results.filter((r) => r.entry.type !== "decision");

  if (decisions.length > 0) {
    lines.push("### Decisions");
    lines.push("");
    for (const r of decisions) {
      lines.push(formatMemoryBullet(r.entry));
    }
    lines.push("");
  }

  if (other.length > 0) {
    lines.push("### Project context");
    lines.push("");
    for (const r of other) {
      lines.push(formatMemoryBullet(r.entry));
    }
    lines.push("");
  }

  lines.push("### How to use AgentOS");
  lines.push("");
  lines.push("- Ask why: `npx agentos memory why \"<topic>\"`");
  lines.push("- Search: `npx agentos memory search \"<query>\"`");
  lines.push('- Record a decision: `npx agentos memory add "We chose X because Y"`');
  lines.push("- Refresh this context: `npx agentos context`");
  lines.push("");

  return lines.join("\n");
}

function formatMemoryBullet(entry: MemoryEntry): string {
  const meta: string[] = [];
  if (entry.evidence?.commit) meta.push(`commit:${entry.evidence.commit}`);
  if (entry.evidence?.pr) meta.push(`PR #${entry.evidence.pr}`);
  if (entry.author) meta.push(entry.author);
  if (entry.createdAt) meta.push(entry.createdAt.slice(0, 10));
  const suffix = meta.length ? ` _(${meta.join(" · ")})_` : "";
  return `- **[${entry.type}]** ${entry.content}${suffix}`;
}

export function formatWhyForAgent(summary: DecisionSummary): string {
  if (summary.confidence === 0) {
    return `No institutional memory for "${summary.query}". Record decisions with agentos memory add.`;
  }
  const lines = [
    `## Why: ${summary.query}`,
    "",
    summary.headline,
    "",
    `**Reason:** ${summary.reason}`,
    "",
  ];
  if (summary.decisions.length) {
    lines.push("**Evidence:**");
    for (const d of summary.decisions.slice(0, 4)) {
      const ev = d.evidence?.commit
        ? ` (commit ${d.evidence.commit})`
        : d.evidence?.pr
          ? ` (PR #${d.evidence.pr})`
          : "";
      lines.push(`- ${d.content}${ev}`);
    }
    lines.push("");
  }
  lines.push(`Confidence: ${Math.round(summary.confidence * 100)}%`);
  return lines.join("\n");
}

export function writeContextFile(
  store: MemoryStore,
  projectRoot: string,
  options: ContextOptions = {}
): string {
  const dir = join(projectRoot, AGENTOS_DIR);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const block = buildContextBlock(store, options);
  const path = join(dir, CONTEXT_FILE);
  const header =
    "<!-- Generated by AgentOS. Do not edit by hand. Run: agentos context -->\n\n";
  writeFileSync(path, header + block, "utf-8");
  return path;
}
